// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI tutor conversation flow.
 *
 * - aiTutorConversation - A function that handles the conversation with the AI tutor.
 * - AiTutorConversationInput - The input type for the aiTutorConversation function.
 * - AiTutorConversationOutput - The return type for the aiTutorConversation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiTutorConversationInputSchema = z.object({
  scenario: z.string().describe('The scenario for the conversation (e.g., airport, cafe, taxi).'),
  language: z.string().describe('The target language for the conversation (e.g., Spanish, French, German, Japanese).'),
  userMessage: z.string().describe('The user message to the AI tutor.'),
});
export type AiTutorConversationInput = z.infer<typeof AiTutorConversationInputSchema>;

const AiTutorConversationOutputSchema = z.object({
  aiResponse: z.string().describe('The AI tutor response to the user message.'),
});
export type AiTutorConversationOutput = z.infer<typeof AiTutorConversationOutputSchema>;

export async function aiTutorConversation(input: AiTutorConversationInput): Promise<AiTutorConversationOutput> {
  return aiTutorConversationFlow(input);
}

const aiTutorConversationPrompt = ai.definePrompt({
  name: 'aiTutorConversationPrompt',
  input: {schema: AiTutorConversationInputSchema},
  output: {schema: AiTutorConversationOutputSchema},
  prompt: `You are an AI tutor specializing in language learning. Your goal is to help users improve their speaking skills and confidence in {{language}}.  The user is currently practicing a conversation in the following scenario: {{scenario}}.  Respond to the user message in a way that is natural, helpful, and encouraging.

User message: {{{userMessage}}}

AI Tutor Response:`,
});

const aiTutorConversationFlow = ai.defineFlow(
  {
    name: 'aiTutorConversationFlow',
    inputSchema: AiTutorConversationInputSchema,
    outputSchema: AiTutorConversationOutputSchema,
  },
  async input => {
    const {output} = await aiTutorConversationPrompt(input);
    return output!;
  }
);
